## AHP 분석을 통한 지수찾기

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import gmean

In [ ]:
inter_score=pd.read_excel('/content/inter_score.xlsx')
q_data=pd.read_csv('/content/서울시 최종 데이터.csv')
poly_near=pd.read_excel('/content/polygon_analysis_finalrealreal.xlsx')

In [ ]:
inter_score

     폴리곤 번호 최외곽 행정동 인접 행정동        IC        OC         IA         OA     INTER
0         1    신사동1   잠실2동    467.24    158.76  193013.11  114631.07  0.002035
1         1    신사동1   잠실7동    122.08    116.82   35673.92   43941.41  0.003001
2         1    신사동1   잠실3동    390.68    307.56  240569.88  251989.29  0.001418
3         1    신사동1    삼전동    143.43     83.66   73154.02   65461.33  0.001638
4         1    신사동1   개포3동  34572.30  34572.30  191333.86  192971.10  0.179921
..      ...     ...    ...       ...       ...        ...        ...       ...
389       6    잠실6동   방이2동  22350.32   9115.45  151369.01  110258.73  0.120269
390       6    잠실6동    석촌동   6143.32   3651.03  113910.34  106386.02  0.044460
391       6    잠실6동   송파1동  12064.22   7717.18  104798.96   90092.62  0.101500
392       6    잠실6동   잠실3동  30275.82  27869.67  240569.88  251989.29  0.118048
393       6    잠실6동   잠실4동  11410.13   9612.51   59673.91   61042.73  0.174149

[394 rows x 8 columns]

In [ ]:
inter_score.columns

Index(['폴리곤 번호', '최외곽 행정동', '인접 행정동', 'IC', 'OC', 'IA', 'OA', 'INTER'], dtype='object')

In [ ]:
q_data

,adm_cd2,행정구역,행정동 면적,행정동별 거주인구,(주말) 행정동별 유동/상주인구,세대당공원면적,normalized_세대당공원면적,추정매출액,버스정류장수,공시지가,상권_변화_지표_명,개업률,폐업률,총 승객수,지하철역수,geometry_y
0,1171063100,가락1동,1.34,20444.776120,2082.213670,2.12,1.137833,6.596725e+10,14,6831820.632,0,0.7,0.9,68117,0,MULTIPOLYGON (((127.11162225485602 37.50039636...
1,1171063200,가락2동,0.96,32250.000000,-6723.412653,50.11,3.933980,5.505595e+10,21,6831820.632,2,2.2,3.1,42065,0,MULTIPOLYGON (((127.13927614960723 37.49565723...
2,1171062000,가락본동,1.13,22063.716810,8762.265432,4.97,1.786747,7.340508e+10,25,6831820.632,3,2.6,3.0,19060,1,MULTIPOLYGON (((127.12390421005378 37.50537105...
3,1153059500,가리봉동,0.40,21877.500000,2727.509805,0.00,0.000000,2.205196e+10,9,3420481.487,2,2.6,3.2,15883,0,MULTIPOLYGON (((126.88605306543074 37.48498340...
4,1154551000,가산동,2.52,9896.031746,7119.547536,0.27,0.239017,1.590000e+11,105,3122667.082,3,2.1,2.4,182141,5,MULTIPOLYGON (((126.88065885796262 37.48596867...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,1117058000,효창동,0.44,24065.909090,-4884.153355,40.24,3.719409,9.702395e+09,15,4996481.970,1,1.1,2.8,25629,1,MULTIPOLYGON (((126.96319962027266 37.54867748...
422,1117051000,후암동,0.86,18481.395350,-5089.514698,0.29,0.254642,2.158173e+10,16,4766103.478,1,3.4,2.7,13515,0,MULTIPOLYGON (((126.98542709369815 37.55374442...
423,1123072000,휘경1동,0.63,21784.126980,4164.461472,0.21,0.190620,2.291680e+10,13,3456644.222,1,3.8,3.7,53804,2,MULTIPOLYGON (((127.0696260938658 37.594882731...
424,1123073000,휘경2동,1.05,23051.428570,-8257.969781,0.47,0.385262,1.817474e+10,18,3456644.222,3,2.0,1.9,23318,3,MULTIPOLYGON (((127.07072007954939 37.59091177...
425,1159060500,흑석동,1.68,17981.547620,-929.756302,27.15,3.337547,4.789078e+10,48,4956485.883,1,2.3,2.1,54306,2,MULTIPOLYGON (((126.97559303658136 37.51229601...

In [ ]:
poly_near

,폴리곤 번호,폴리곤 좌표,폴리곤 행정동,폴리곤 최외곽 행정동,폴리곤 인접행정동
0,1,"(127.018071,37.476604);(127.016840,37.475967);...","논현1동, 논현2동, 대치1동, 대치2동, 대치4동, 반포4동, 삼성1동, 삼성2동...","신사동1, 논현1동, 역삼1동, 서초4동, 반포4동, 서초3동, 서초1동, 서초2동...","잠실2동, 잠실7동, 잠실3동, 삼전동, 개포3동, 개포2동, 개포1동, 도곡2동..."
1,2,"(126.905973,37.515680);(126.903863,37.514931);...","여의동, 영등포동",영등포동,"당산1동, 당산2동, 문래동, 영등포본동, 신길1동"
2,3,"(126.972061,37.523040);(126.970180,37.522874);...",한강로동,한강로동,"남영동, 서빙고동, 용산2가동, 원효로1동, 원효로2동, 이촌1동, 이촌2동"
3,4,"(126.910652,37.558031);(126.912011,37.558262);...","서교동, 신촌동","서교동, 신촌동","대흥동, 망원1동, 북아현동, 서강동, 성산1동, 아현동, 연남동, 연희동, 염리동..."
4,5,"(126.983744,37.553036);(126.983067,37.553404);...","광희동, 명동, 사직동, 소공동, 을지로동, 종로1·2·3·4가동, 회현동","광희동, 명동, 사직동, 소공동, 을지로동, 종로1·2·3·4가동, 회현동","가회동, 교남동, 남영동, 무악동, 삼청동, 신당동, 이화동, 장충동, 종로5·6가..."
5,6,"(127.098881,37.514872);(127.098661,37.515158);...",잠실6동,잠실6동,"방이2동, 석촌동, 송파1동, 잠실3동, 잠실4동"

In [ ]:
df = q_data.copy()
df

,adm_cd2,행정구역,행정동 면적,행정동별 거주인구,(주말) 행정동별 유동/상주인구,세대당공원면적,normalized_세대당공원면적,추정매출액,버스정류장수,공시지가,상권_변화_지표_명,개업률,폐업률,총 승객수,지하철역수,geometry_y
0,1171063100,가락1동,1.34,20444.776120,2082.213670,2.12,1.137833,6.596725e+10,14,6831820.632,0,0.7,0.9,68117,0,MULTIPOLYGON (((127.11162225485602 37.50039636...
1,1171063200,가락2동,0.96,32250.000000,-6723.412653,50.11,3.933980,5.505595e+10,21,6831820.632,2,2.2,3.1,42065,0,MULTIPOLYGON (((127.13927614960723 37.49565723...
2,1171062000,가락본동,1.13,22063.716810,8762.265432,4.97,1.786747,7.340508e+10,25,6831820.632,3,2.6,3.0,19060,1,MULTIPOLYGON (((127.12390421005378 37.50537105...
3,1153059500,가리봉동,0.40,21877.500000,2727.509805,0.00,0.000000,2.205196e+10,9,3420481.487,2,2.6,3.2,15883,0,MULTIPOLYGON (((126.88605306543074 37.48498340...
4,1154551000,가산동,2.52,9896.031746,7119.547536,0.27,0.239017,1.590000e+11,105,3122667.082,3,2.1,2.4,182141,5,MULTIPOLYGON (((126.88065885796262 37.48596867...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,1117058000,효창동,0.44,24065.909090,-4884.153355,40.24,3.719409,9.702395e+09,15,4996481.970,1,1.1,2.8,25629,1,MULTIPOLYGON (((126.96319962027266 37.54867748...
422,1117051000,후암동,0.86,18481.395350,-5089.514698,0.29,0.254642,2.158173e+10,16,4766103.478,1,3.4,2.7,13515,0,MULTIPOLYGON (((126.98542709369815 37.55374442...
423,1123072000,휘경1동,0.63,21784.126980,4164.461472,0.21,0.190620,2.291680e+10,13,3456644.222,1,3.8,3.7,53804,2,MULTIPOLYGON (((127.0696260938658 37.594882731...
424,1123073000,휘경2동,1.05,23051.428570,-8257.969781,0.47,0.385262,1.817474e+10,18,3456644.222,3,2.0,1.9,23318,3,MULTIPOLYGON (((127.07072007954939 37.59091177...
425,1159060500,흑석동,1.68,17981.547620,-929.756302,27.15,3.337547,4.789078e+10,48,4956485.883,1,2.3,2.1,54306,2,MULTIPOLYGON (((126.97559303658136 37.51229601...

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.preprocessing import StandardScaler


columns_to_analyze = ['행정동별 거주인구', 'normalized_세대당공원면적', '추정매출액', '개업률', '폐업률']

# 1. 변동계수 계산
def coefficient_of_variation(data):
    return np.std(data) / np.mean(data)

cv_values = {col: coefficient_of_variation(df[col]) for col in columns_to_analyze}

# 2. 정보 이득 계산 (연속형 변수를 위한 근사치)
def information_gain(data):
    _, bins = np.histogram(data, bins='auto')
    hist, _ = np.histogram(data, bins=bins)
    prob = hist / len(data)
    entropy = -np.sum(prob * np.log2(prob + 1e-10))
    return 1 - entropy / np.log2(len(bins) - 1)

ig_values = {col: information_gain(df[col]) for col in columns_to_analyze}

In [ ]:
# 3. 변동계수와 정보 이득을 결합하여 중요도 점수 계산
importance_scores = {col: cv_values[col] * ig_values[col] for col in columns_to_analyze}

# 4. 쌍대비교 행렬 생성
n = len(columns_to_analyze)
pairwise_matrix = np.ones((n, n))

for i in range(n):
    for j in range(i+1, n):
        col_i = columns_to_analyze[i]
        col_j = columns_to_analyze[j]
        ratio = importance_scores[col_i] / importance_scores[col_j]
        pairwise_matrix[i, j] = min(9, max(1/9, ratio))  # 1/9에서 9 사이의 값으로 제한
        pairwise_matrix[j, i] = 1 / pairwise_matrix[i, j]

# 5. 가중치 계산 (기존 코드 사용)
def calculate_weights(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    max_index = np.argmax(eigenvalues)
    eigenvalues = np.real(eigenvalues[max_index])
    eigenvectors = np.real(eigenvectors[:, max_index])
    return eigenvectors / np.sum(eigenvectors)

weights = calculate_weights(pairwise_matrix)

# 6. 일관성 비율 검증 (기존 코드 사용)
def consistency_ratio(matrix, weights):
    n = len(matrix)
    lambda_max = np.sum(np.dot(matrix, weights) / weights)
    consistency_index = (lambda_max - n) / (n - 1)
    random_index = {3: 0.58, 4: 0.9, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
    return consistency_index / random_index[n]

cr = consistency_ratio(pairwise_matrix, weights)
print(f"Consistency Ratio: {cr}")

# 7. Q(x) 지수 계산
scaler = StandardScaler()
normalized_df = pd.DataFrame(scaler.fit_transform(df[columns_to_analyze]), columns=columns_to_analyze)

def calculate_index(row):
    return np.dot(row[columns_to_analyze].values, weights)

df['Q(x)'] = normalized_df.apply(calculate_index, axis=1)

# 결과 출력
print("\n변수별 가중치:")
for col, weight in zip(columns_to_analyze, weights):
    print(f"{col}: {weight:.4f}")

Consistency Ratio: 4.464424094978117

변수별 가중치:
행정동별 거주인구: 0.0500
normalized_세대당공원면적: 0.3089
추정매출액: 0.4588
개업률: 0.0639
폐업률: 0.1184

In [ ]:
print('Q_data_final columns:',Q_data_final.columns)
print('poly_near columns:', poly_near.columns)
print('q_data columns:', q_data.columns)

Q_data_final columns: Index(['행정구역', 'Q(x)'], dtype='object')
poly_near columns: Index(['폴리곤 번호', '폴리곤 좌표', '폴리곤 행정동', '폴리곤 최외곽 행정동', '폴리곤 인접행정동'], dtype='object')
q_data columns: Index(['adm_cd2', '행정구역', '행정동 면적', '행정동별 거주인구', '(주말) 행정동별 유동/상주인구',
       '세대당공원면적', 'normalized_세대당공원면적', '추정매출액', '버스정류장수', '공시지가',
       '상권_변화_지표_명', '개업률', '폐업률', '총 승객수', '지하철역수', 'geometry_y'],
      dtype='object')

In [ ]:
Q_data_final=df[['행정구역', 'Q(x)']]
Q_data_final

     행정구역      Q(x)
0    가락1동 -0.253719
1    가락2동  0.695335
2    가락본동  0.415726
3    가리봉동 -0.408325
4     가산동  0.747911
..    ...       ...
421   효창동  0.042572
422   후암동 -0.382502
423  휘경1동 -0.190109
424  휘경2동 -0.600367
425   흑석동  0.306345

[426 rows x 2 columns]

# 그래프

In [ ]:
!pip install networkx pulp

Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (3.3)
Requirement already satisfied: pulp in /usr/local/lib/python3.10/dist-packages (2.9.0)

In [ ]:
# import pandas as pd
# import networkx as nx
# import pulp

# # 데이터 로드
# Q_data_final = df[['행정구역', 'Q(x)']]
# inter_score = pd.read_excel('/content/inter_score.xlsx')
# poly_near = pd.read_excel('/content/polygon_analysis_finalrealreal.xlsx')

# # 데이터 정제 함수
# def clean_district_names(name):
#     return [district.strip() for district in name.split(',')]

# # poly_near 데이터프레임 정제
# poly_near['폴리곤 최외곽 행정동'] = poly_near['폴리곤 최외곽 행정동'].apply(clean_district_names)
# poly_near['폴리곤 인접행정동'] = poly_near['폴리곤 인접행정동'].apply(clean_district_names)
# poly_near = poly_near.explode('폴리곤 최외곽 행정동').explode('폴리곤 인접행정동')

# # 그래프 생성
# G = nx.Graph()

# # 노드 추가
# for _, row in inter_score.iterrows():
#     outer_q = Q_data_final[Q_data_final['행정구역'] == row['최외곽 행정동']]['Q(x)'].values[0] if not Q_data_final[Q_data_final['행정구역'] == row['최외곽 행정동']].empty else 0
#     adjacent_q = Q_data_final[Q_data_final['행정구역'] == row['인접 행정동']]['Q(x)'].values[0] if not Q_data_final[Q_data_final['행정구역'] == row['인접 행정동']].empty else 0

#     G.add_node(row['최외곽 행정동'], q=outer_q, is_outer=True)
#     G.add_node(row['인접 행정동'], q=adjacent_q, is_outer=False)

# # 엣지 추가
# for _, row in inter_score.iterrows():
#     G.add_edge(row['최외곽 행정동'], row['인접 행정동'], weight=row['INTER'])

# # 최적화 함수 수정
# def optimize_linear_park(G, polygon, min_nodes, max_nodes):
#     if len(G) == 0:
#         print(f"폴리곤 {polygon}의 그래프가 비어있습니다.")
#         return [], []

#     model = pulp.LpProblem("Linear_Park_Optimization", pulp.LpMinimize)
#     node_vars = pulp.LpVariable.dicts("Node", G.nodes(), cat='Binary')
#     edge_vars = pulp.LpVariable.dicts("Edge", G.edges(), cat='Binary')

#     model += pulp.lpSum([edge_vars[e] * G[e[0]][e[1]]['weight'] for e in G.edges()])

#     model += pulp.lpSum(node_vars.values()) >= min_nodes
#     model += pulp.lpSum(node_vars.values()) <= max_nodes
#     model += pulp.lpSum([node_vars[n] for n in G.nodes() if G.nodes[n]['is_outer']]) >= 1

#     for e in G.edges():
#         model += edge_vars[e] <= node_vars[e[0]]
#         model += edge_vars[e] <= node_vars[e[1]]

#     for n in G.nodes():
#         connected_edges = [e for e in G.edges(n) if e in edge_vars]
#         if connected_edges:
#             model += pulp.lpSum([edge_vars[e] for e in connected_edges]) >= 2 * node_vars[n] - 1

#     model.solve()

#     selected_nodes = [n for n in G.nodes() if node_vars[n].value() > 0.5]
#     selected_edges = [e for e in G.edges() if e in edge_vars and edge_vars[e].value() > 0.5]

#     return selected_nodes, selected_edges

# # 각 폴리곤에 대해 최적화 실행
# results = {}
# for polygon in range(1, 7):
#     polygon_nodes = set(poly_near[poly_near['폴리곤 번호'] == polygon]['폴리곤 최외곽 행정동'].tolist() +
#                         poly_near[poly_near['폴리곤 번호'] == polygon]['폴리곤 인접행정동'].tolist())
#     polygon_graph = G.subgraph(polygon_nodes)

#     print(f"폴리곤 {polygon} 노드 수: {len(polygon_graph.nodes())}")
#     print(f"폴리곤 {polygon} 엣지 수: {len(polygon_graph.edges())}")

#     for num_nodes in range(3, 6):
#         nodes, edges = optimize_linear_park(polygon_graph, polygon, num_nodes, num_nodes)
#         results[(polygon, num_nodes)] = (nodes, edges)

# # 결과 출력
# for (polygon, num_nodes), (nodes, edges) in results.items():
#     print(f"폴리곤 {polygon}, {num_nodes}개 동 통과:")
#     print("선택된 노드:", nodes)
#     print("선택된 엣지:", edges)
#     print()

폴리곤 1 노드 수: 30
폴리곤 1 엣지 수: 216
폴리곤 2 노드 수: 6
폴리곤 2 엣지 수: 5
폴리곤 3 노드 수: 8
폴리곤 3 엣지 수: 7
폴리곤 4 노드 수: 14
폴리곤 4 엣지 수: 24
폴리곤 5 노드 수: 24
폴리곤 5 엣지 수: 119
폴리곤 6 노드 수: 6
폴리곤 6 엣지 수: 5
폴리곤 1, 3개 동 통과:
선택된 노드: ['역삼2동', '도곡1동', '방배4동']
선택된 엣지: [('역삼2동', '방배4동')]

폴리곤 1, 4개 동 통과:
선택된 노드: ['역삼2동', '도곡1동', '반포2동', '방배4동']
선택된 엣지: [('역삼2동', '방배4동')]

폴리곤 1, 5개 동 통과:
선택된 노드: ['역삼2동', '반포3동', '도곡1동', '반포2동', '방배4동']
선택된 엣지: [('역삼2동', '방배4동')]

폴리곤 2, 3개 동 통과:
선택된 노드: ['영등포동', '영등포본동', '신길1동']
선택된 엣지: [('영등포동', '신길1동')]

폴리곤 2, 4개 동 통과:
선택된 노드: ['영등포동', '문래동', '영등포본동', '신길1동']
선택된 엣지: [('영등포동', '신길1동')]

폴리곤 2, 5개 동 통과:
선택된 노드: ['당산1동', '영등포동', '문래동', '영등포본동', '신길1동']
선택된 엣지: [('당산1동', '영등포동'), ('영등포동', '신길1동')]

폴리곤 3, 3개 동 통과:
선택된 노드: ['용산2가동', '한강로동', '이촌2동']
선택된 엣지: [('용산2가동', '한강로동'), ('한강로동', '이촌2동')]

폴리곤 3, 4개 동 통과:
선택된 노드: ['남영동', '용산2가동', '한강로동', '이촌2동']
선택된 엣지: [('남영동', '한강로동'), ('용산2가동', '한강로동'), ('한강로동', '이촌2동')]

폴리곤 3, 5개 동 통과:
선택된 노드: ['남영동', '용산2가동', '서빙고동', '한강로동', '이촌2동']
선택된 엣지: [('남영동', '한강로동'), ('용산2가동', '한강로동'), ('서빙고동', '한강로동'), ('한강로동', '이촌2동')]

폴리곤 4, 3개 동 통과:
선택된 노드: ['신촌동', '성산1동', '망원1동']
선택된 엣지: [('신촌동', '망원1동')]

폴리곤 4, 4개 동 통과:
선택된 노드: ['신촌동', '성산1동', '망원1동', '연남동']
선택된 엣지: [('신촌동', '망원1동')]

폴리곤 4, 5개 동 통과:
선택된 노드: ['신촌동', '성산1동', '연희동', '망원1동', '연남동']
선택된 엣지: [('신촌동', '망원1동')]

폴리곤 5, 3개 동 통과:
선택된 노드: ['종로5·6가동', '창신1동', '소공동']
선택된 엣지: [('종로5·6가동', '소공동'), ('창신1동', '소공동')]

폴리곤 5, 4개 동 통과:
선택된 노드: ['신당동', '사직동', '창신1동', '소공동']
선택된 엣지: [('신당동', '사직동'), ('사직동', '창신1동'), ('창신1동', '소공동')]

폴리곤 5, 5개 동 통과:
선택된 노드: ['청파동', '혜화동', '을지로동', '창신1동', '소공동']
선택된 엣지: [('청파동', '을지로동'), ('혜화동', '을지로동'), ('을지로동', '창신1동'), ('창신1동', '소공동')]

폴리곤 6, 3개 동 통과:
선택된 노드: ['송파1동', '석촌동', '잠실6동']
선택된 엣지: [('송파1동', '잠실6동'), ('석촌동', '잠실6동')]

폴리곤 6, 4개 동 통과:
선택된 노드: ['잠실3동', '송파1동', '석촌동', '잠실6동']
선택된 엣지: [('잠실3동', '잠실6동'), ('송파1동', '잠실6동'), ('석촌동', '잠실6동')]

폴리곤 6, 5개 동 통과:
선택된 노드: ['잠실3동', '송파1동', '방이2동', '석촌동', '잠실6동']
선택된 엣지: [('잠실3동', '잠실6동'), ('송파1동', '잠실6동'), ('방이2동', '잠실6동'), ('석촌동', '잠실6동')]

In [ ]:
def optimize_linear_park(G, polygon, Q_data_final):
    model = pulp.LpProblem(f"Linear_Park_Optimization_Polygon_{polygon}", pulp.LpMinimize)

    # 결정 변수
    node_vars = pulp.LpVariable.dicts("Node", G.nodes(), cat='Binary')
    edge_vars = pulp.LpVariable.dicts("Edge", G.edges(), cat='Binary')

    # 목적 함수: 선택된 엣지의 가중치 합 최소화
    edge_weights = pulp.lpSum([edge_vars[e] * G[e[0]][e[1]]['weight'] for e in G.edges()])
    model += edge_weights

    # 제약 조건
    # 1. 정확히 3개의 노드 선택
    model += pulp.lpSum(node_vars.values()) == 3

    # 2. 최소 하나의 최외곽 지역 포함
    model += pulp.lpSum([node_vars[n] for n in G.nodes() if G.nodes[n]['is_outer']]) >= 1

    # 3. 선택된 노드는 연결되어야 함
    for e in G.edges():
        model += edge_vars[e] <= node_vars[e[0]]
        model += edge_vars[e] <= node_vars[e[1]]

    # 4. 선택된 노드들은 경로를 형성해야 함 (인접-최외곽-인접)
    model += pulp.lpSum(edge_vars.values()) == 2

    # 5. Q(x) 값 고려
    outer_nodes = [n for n in G.nodes() if G.nodes[n]['is_outer']]
    adjacent_nodes = [n for n in G.nodes() if not G.nodes[n]['is_outer']]

    outer_q = sum([Q_data_final.loc[Q_data_final['행정구역'] == n, 'Q(x)'].values[0] for n in outer_nodes if n in Q_data_final['행정구역'].values])
    adjacent_q = sum([Q_data_final.loc[Q_data_final['행정구역'] == n, 'Q(x)'].values[0] for n in adjacent_nodes if n in Q_data_final['행정구역'].values])

    if adjacent_q != 0:
        q_ratio = outer_q / adjacent_q
    else:
        q_ratio = 1  # 0으로 나누는 것을 방지

    # Q(x) 비율을 목적 함수에 추가 (최대화하려는 값이므로 음수를 사용)
    q_objective = -q_ratio * 0.01  # 가중치를 조정하여 INTER 값과 균형을 맞춤
    model += q_objective

    # 모델 풀기
    model.solve()

    # 결과 추출
    selected_nodes = [n for n in G.nodes() if node_vars[n].value() > 0.5]
    selected_edges = [e for e in G.edges() if edge_vars[e].value() > 0.5]

    # 목적 함수 값 계산
    edge_weight_sum = sum(G[e[0]][e[1]]['weight'] for e in selected_edges)
    q_value = q_ratio * 0.01 if selected_nodes else 0
    objective_value = edge_weight_sum - q_value

    return selected_nodes, selected_edges, objective_value

# 각 폴리곤에 대해 최적화 실행
results = {}
for polygon in range(1, 7):
    polygon_nodes = set(poly_near[poly_near['폴리곤 번호'] == polygon]['폴리곤 최외곽 행정동'].tolist() +
                        poly_near[poly_near['폴리곤 번호'] == polygon]['폴리곤 인접행정동'].tolist())
    polygon_graph = G.subgraph(polygon_nodes)

    nodes, edges, objective_value = optimize_linear_park(polygon_graph, polygon, Q_data_final)
    results[polygon] = (nodes, edges, objective_value)

# 결과 출력 및 데이터프레임 생성
optimal_paths = []
for polygon, (nodes, edges, objective_value) in results.items():
    print(f"폴리곤 {polygon}:")
    print("선택된 노드:", nodes)
    print("선택된 엣지:", edges)
    print("목적 함수 값:", objective_value)
    print()

    optimal_paths.append({
        'Polygon': polygon,
        'Selected_Nodes': ', '.join(nodes),
        'Selected_Edges': ', '.join([f"({e[0]}-{e[1]})" for e in edges]),
        'Objective_Value': objective_value
    })

optimal_paths_df = pd.DataFrame(optimal_paths)
print("최적 경로 정보:")
print(optimal_paths_df)

폴리곤 1:
선택된 노드: ['논현1동', '개포1동', '도곡2동']
선택된 엣지: [('논현1동', '개포1동'), ('논현1동', '도곡2동')]
목적 함수 값: 0.1988870383486497

폴리곤 2:
선택된 노드: ['당산2동', '당산1동', '영등포동']
선택된 엣지: [('당산2동', '영등포동'), ('당산1동', '영등포동')]
목적 함수 값: 2.9065581794430972

폴리곤 3:
선택된 노드: ['남영동', '용산2가동', '한강로동']
선택된 엣지: [('남영동', '한강로동'), ('용산2가동', '한강로동')]
목적 함수 값: 0.14521459348996674

폴리곤 4:
선택된 노드: ['대흥동', '홍제1동', '서교동']
선택된 엣지: [('대흥동', '서교동'), ('홍제1동', '서교동')]
목적 함수 값: -0.029313249225618912

폴리곤 5:
선택된 노드: ['교남동', '가회동', '명동']
선택된 엣지: [('교남동', '명동'), ('가회동', '명동')]
목적 함수 값: 0.05230381615537378

폴리곤 6:
선택된 노드: ['방이2동', '석촌동', '잠실6동']
선택된 엣지: [('방이2동', '잠실6동'), ('석촌동', '잠실6동')]
목적 함수 값: 0.09924180706092658

최적 경로 정보:
   Polygon    Selected_Nodes            Selected_Edges  Objective_Value
0        1  논현1동, 개포1동, 도곡2동  (논현1동-개포1동), (논현1동-도곡2동)         0.198887
1        2  당산2동, 당산1동, 영등포동  (당산2동-영등포동), (당산1동-영등포동)         2.906558
2        3  남영동, 용산2가동, 한강로동  (남영동-한강로동), (용산2가동-한강로동)         0.145215
3        4    대흥동, 홍제1동, 서교동     (대흥동-서교동), (홍제1동-서교동)        -0.029313
4        5      교남동, 가회동, 명동        (교남동-명동), (가회동-명동)         0.052304
5        6   방이2동, 석촌동, 잠실6동   (방이2동-잠실6동), (석촌동-잠실6동)         0.099242

/usr/local/lib/python3.10/dist-packages/pulp/pulp.py:1657: UserWarning: Overwriting previously set objective.
  warnings.warn("Overwriting previously set objective.")

In [ ]:
import matplotlib.pyplot as plt
import itertools  # itertools 모듈 임포트

In [ ]:
# 데이터 정제 함수
def clean_district_names(name):
    return [district.strip() for district in name.split(',')]

# poly_near 데이터프레임 정제
poly_near['폴리곤 최외곽 행정동'] = poly_near['폴리곤 최외곽 행정동'].apply(clean_district_names)
poly_near['폴리곤 인접행정동'] = poly_near['폴리곤 인접행정동'].apply(clean_district_names)
poly_near = poly_near.explode('폴리곤 최외곽 행정동').explode('폴리곤 인접행정동')

# 그래프 생성
G = nx.Graph()

# 노드 추가
for _, row in inter_score.iterrows():
    outer_q = Q_data_final[Q_data_final['행정구역'] == row['최외곽 행정동']]['Q(x)'].values[0] if not Q_data_final[Q_data_final['행정구역'] == row['최외곽 행정동']].empty else 0
    adjacent_q = Q_data_final[Q_data_final['행정구역'] == row['인접 행정동']]['Q(x)'].values[0] if not Q_data_final[Q_data_final['행정구역'] == row['인접 행정동']].empty else 0

    G.add_node(row['최외곽 행정동'], q=outer_q, is_outer=True)
    G.add_node(row['인접 행정동'], q=adjacent_q, is_outer=False)

# 엣지 추가
for _, row in inter_score.iterrows():
    G.add_edge(row['최외곽 행정동'], row['인접 행정동'], weight=row['INTER'])
def optimize_linear_park_exact(G, polygon):
    # 그래프에 노드가 3개 미만인 경우 처리
    if len(G.nodes()) < 3:
        print(f"폴리곤 {polygon}에는 노드가 3개 미만입니다.")
        return [], []

    # 모든 조합 생성
    node_combinations = list(itertools.combinations(G.nodes(), 3))
    best_combination = None
    best_score = float('inf')

    for combination in node_combinations:
        # 조합의 엣지 찾기
        edges = [(combination[0], combination[1]), (combination[1], combination[2]), (combination[0], combination[2])]
        edge_weights = [G[edge[0]][edge[1]]['weight'] for edge in edges if G.has_edge(edge[0], edge[1])]

        # 모든 엣지가 존재해야만 평가
        if len(edge_weights) == len(edges):
            score = sum(edge_weights)  # 예를 들어, 가중치 합계로 최적화
            if score < best_score:
                best_score = score
                best_combination = combination

    return best_combination, [(best_combination[0], best_combination[1]), (best_combination[1], best_combination[2]), (best_combination[0], best_combination[2])] if best_combination else []

# 각 폴리곤에 대해 최적화 실행
results = {}
for polygon in range(1, 7):
    polygon_nodes = set(poly_near[poly_near['폴리곤 번호'] == polygon]['폴리곤 최외곽 행정동'].tolist() +
                        poly_near[poly_near['폴리곤 번호'] == polygon]['폴리곤 인접행정동'].tolist())
    polygon_graph = G.subgraph(polygon_nodes)

    print(f"폴리곤 {polygon} 노드 수: {len(polygon_graph.nodes())}")
    print(f"폴리곤 {polygon} 엣지 수: {len(polygon_graph.edges())}")

    nodes, edges = optimize_linear_park_exact(polygon_graph, polygon)
    results[polygon] = (nodes, edges if edges else [])

# 결과 출력 및 CSV 저장
output_data = []
for polygon, (nodes, edges) in results.items():
    print(f"폴리곤 {polygon}, 선택된 노드:", nodes)
    print("선택된 엣지:", edges)
    output_data.append((polygon, nodes, edges))

output_df = pd.DataFrame(output_data, columns=['폴리곤 번호', '선택된 노드', '선택된 엣지'])
output_df.to_csv('top3_optimal.csv', index=False)

폴리곤 1 노드 수: 30
폴리곤 1 엣지 수: 216
폴리곤 2 노드 수: 6
폴리곤 2 엣지 수: 5
폴리곤 3 노드 수: 8
폴리곤 3 엣지 수: 7
폴리곤 4 노드 수: 14
폴리곤 4 엣지 수: 24
폴리곤 5 노드 수: 24
폴리곤 5 엣지 수: 119
폴리곤 6 노드 수: 6
폴리곤 6 엣지 수: 5
폴리곤 1, 선택된 노드: None
선택된 엣지: []
폴리곤 2, 선택된 노드: None
선택된 엣지: []
폴리곤 3, 선택된 노드: None
선택된 엣지: []
폴리곤 4, 선택된 노드: None
선택된 엣지: []
폴리곤 5, 선택된 노드: None
선택된 엣지: []
폴리곤 6, 선택된 노드: None
선택된 엣지: []

In [ ]:
top3_df

    Polygon  Rank    Selected_Nodes            Selected_Edges  Objective_Value
0         1     1  논현1동, 개포1동, 도곡2동  (논현1동-개포1동), (논현1동-도곡2동)         0.198887
1         1     2  논현1동, 개포1동, 도곡2동  (논현1동-개포1동), (논현1동-도곡2동)         0.198887
2         1     3  논현1동, 개포1동, 도곡2동  (논현1동-개포1동), (논현1동-도곡2동)         0.198887
3         2     1  당산2동, 당산1동, 영등포동  (당산2동-영등포동), (당산1동-영등포동)         2.906558
4         2     2  당산2동, 당산1동, 영등포동  (당산2동-영등포동), (당산1동-영등포동)         2.906558
5         2     3  당산2동, 당산1동, 영등포동  (당산2동-영등포동), (당산1동-영등포동)         2.906558
6         3     1  남영동, 용산2가동, 한강로동  (남영동-한강로동), (용산2가동-한강로동)         0.145215
7         3     2  남영동, 용산2가동, 한강로동  (남영동-한강로동), (용산2가동-한강로동)         0.145215
8         3     3  남영동, 용산2가동, 한강로동  (남영동-한강로동), (용산2가동-한강로동)         0.145215
9         4     1    대흥동, 홍제1동, 서교동     (대흥동-서교동), (홍제1동-서교동)        -0.029313
10        4     2    대흥동, 홍제1동, 서교동     (대흥동-서교동), (홍제1동-서교동)        -0.029313
11        4     3    대흥동, 홍제1동, 서교동     (대흥동-서교동), (홍제1동-서교동)        -0.029313
12        5     1      교남동, 가회동, 명동        (교남동-명동), (가회동-명동)         0.052304
13        5     2      교남동, 가회동, 명동        (교남동-명동), (가회동-명동)         0.052304
14        5     3      교남동, 가회동, 명동        (교남동-명동), (가회동-명동)         0.052304
15        6     1   방이2동, 석촌동, 잠실6동   (방이2동-잠실6동), (석촌동-잠실6동)         0.099242
16        6     2   방이2동, 석촌동, 잠실6동   (방이2동-잠실6동), (석촌동-잠실6동)         0.099242
17        6     3   방이2동, 석촌동, 잠실6동   (방이2동-잠실6동), (석촌동-잠실6동)         0.099242

In [ ]:
!pip install folium

Requirement already satisfied: folium in /usr/local/lib/python3.10/dist-packages (0.17.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from folium) (0.7.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from folium) (1.26.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.10/dist-packages (from folium) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.9->folium) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (2024.8.30)

In [ ]:
import pandas as pd
import folium
from folium import FeatureGroup, LayerControl
import networkx as nx
import geopandas as gpd
from shapely.geometry import Polygon

In [ ]:
import pandas as pd
import geopandas as gpd
import folium
from shapely.wkt import loads
from shapely.geometry import MultiPolygon, Point

# 올바른 형식으로 변환하는 함수
def convert_to_multipolygon(coord_str):
    if not coord_str or pd.isna(coord_str):  # 비어있거나 NaN인 경우
        return None

    coords = coord_str.split(';')

    # 좌표 형식이 유효한지 확인
    valid_coords = []
    for coord in coords:
        try:
            x, y = coord.split(',')
            valid_coords.append(f"{x.strip()} {y.strip()}")
        except ValueError:
            continue  # 잘못된 좌표는 무시

    if len(valid_coords) < 3:  # 최소 3개 이상의 좌표가 필요
        return None

    coords_str = ', '.join(valid_coords)
    multipolygon_str = f'MULTIPOLYGON(({coords_str}))'

    return loads(multipolygon_str)  # 문자열을 실제 geometry로 변환

# 데이터프레임을 GeoDataFrame으로 변환
poly_near['폴리곤 좌표'] = poly_near['폴리곤 좌표'].apply(convert_to_multipolygon)
poly_near = poly_near[poly_near['폴리곤 좌표'].notna()]  # 유효한 좌표만 필터링
gdf_poly = gpd.GeoDataFrame(poly_near, geometry='폴리곤 좌표').set_crs(epsg=4326)

# 행정구역 GeoDataFrame 생성
gdf_q_data = gpd.GeoDataFrame(q_data, geometry='geometry_y')  # geometry_y를 직접 사용

# 지도 생성
m = folium.Map(location=[37.5, 127.0], zoom_start=12)

# 폴리곤 테두리 추가
# 폴리곤 좌표 시각화 (초록색 테두리)
for idx, row in poly_near.iterrows():
    polygon_coords = row['폴리곤 좌표'].strip("()").split(';')
    polygon_coords = [(float(lon), float(lat)) for lon, lat in (coord.split(',') for coord in polygon_coords)]
    folium.Polygon(locations=polygon_coords, color='green', fill=False).add_to(m)


# 최적 경로 시각화
for idx, row in optimal_paths_df.iterrows():
    selected_nodes = row['Selected_Nodes'].strip("[]").replace("'", "").split(', ')
    selected_edges = row['Selected_Edges'].strip("()").replace("'", "").split(', ')

    # 노드 경로 추가 (빨간색)
    node_coords = []
    for node in selected_nodes:
        geom = gdf_q_data[gdf_q_data['행정구역'] == node]['geometry_y']
        if not geom.empty:
            node_coords.append(geom.values[0].representative_point())  # 중심점 사용

    folium.PolyLine(locations=[(pt.y, pt.x) for pt in node_coords], color='red', weight=3).add_to(m)

    # 엣지 경로 추가 (파란색)
    for edge in selected_edges:
        start_node, end_node = edge.split('-')

        start_geom = gdf_q_data[gdf_q_data['행정구역'] == start_node]['geometry_y']
        end_geom = gdf_q_data[gdf_q_data['행정구역'] == end_node]['geometry_y']

        if not start_geom.empty and not end_geom.empty:
            edge_coords = [
                (start_geom.values[0].representative_point().y, start_geom.values[0].representative_point().x),
                (end_geom.values[0].representative_point().y, end_geom.values[0].representative_point().x)
            ]
            folium.PolyLine(locations=edge_coords, color='blue', weight=2).add_to(m)
        else:
            print(f"경고: '{start_node}' 또는 '{end_node}'에 대한 경계가 없습니다.")

# HTML 파일로 저장
m.save('optimized_route_map.html')

경고: '논현1동' 또는 '개포1동)'에 대한 경계가 없습니다.
경고: '(논현1동' 또는 '도곡2동'에 대한 경계가 없습니다.
경고: '당산2동' 또는 '영등포동)'에 대한 경계가 없습니다.
경고: '(당산1동' 또는 '영등포동'에 대한 경계가 없습니다.
경고: '남영동' 또는 '한강로동)'에 대한 경계가 없습니다.
경고: '(용산2가동' 또는 '한강로동'에 대한 경계가 없습니다.
경고: '대흥동' 또는 '서교동)'에 대한 경계가 없습니다.
경고: '(홍제1동' 또는 '서교동'에 대한 경계가 없습니다.
경고: '교남동' 또는 '명동)'에 대한 경계가 없습니다.
경고: '(가회동' 또는 '명동'에 대한 경계가 없습니다.
경고: '방이2동' 또는 '잠실6동)'에 대한 경계가 없습니다.
경고: '(석촌동' 또는 '잠실6동'에 대한 경계가 없습니다.