In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import geopandas as gpd

In [ ]:
# sales_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/sales.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/sales.csv'

In [ ]:
sales_df.head()

,ADSTRD_NM,ADSTRD_CD,SUM_SELNG_AMT,ADM_NM,ADM_CD,geometry
0,가락1동,11710631.0,6.596725e+10,가락1동,11240660,POLYGON ((209780.90485994637 544511.1612698265...
1,가락2동,11710632.0,5.505595e+10,가락2동,11240670,POLYGON ((212324.33494913927 544030.4497464107...
2,가락본동,11710620.0,7.340508e+10,가락본동,11240650,POLYGON ((211105.04751630727 543660.6932034456...
3,가리봉동,11530595.0,2.205196e+10,가리봉동,11170700,POLYGON ((189438.67265243208 543118.8918221833...
4,가산동,11545510.0,1.590000e+11,가산동,11180510,POLYGON ((189333.22378344863 542985.3764552184...

In [ ]:
sales_df.rename(columns={'ADSTRD_NM': '행정구역', 'SUM_SELNG_AMT': '추정매출액'}, inplace=True)
sales_df=sales_df[['행정구역','추정매출액','geometry']]

In [ ]:
park_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/세대당녹지공원면적 데이터(장준필)/merged.csv",encoding="euc-kr")

In [ ]:
park_df

,adm_nm,adm_cd,adm_cd2,sgg,sido,sidonm,temp,sggnm,adm_cd8,geometry,행정구역ID,행정구역,세대당공원면적,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,서울특별시 종로구 사직동,1101053,1111053000,11110,11,서울특별시,사직동,종로구,11010530,MULTIPOLYGON (((126.97688884274817 37.57565077...,1111053000,사직동,60.79,NaN,True,True
1,서울특별시 종로구 삼청동,1101054,1111054000,11110,11,서울특별시,삼청동,종로구,11010540,MULTIPOLYGON (((126.98268938649305 37.59506551...,1111054000,삼청동,956.51,NaN,True,True
2,서울특별시 종로구 부암동,1101055,1111055000,11110,11,서울특별시,부암동,종로구,11010550,MULTIPOLYGON (((126.97585113775686 37.59656422...,1111055000,부암동,0.00,NaN,True,True
3,서울특별시 종로구 평창동,1101056,1111056000,11110,11,서울특별시,평창동,종로구,11010560,MULTIPOLYGON (((126.97507466788086 37.63138628...,1111056000,평창동,1.14,NaN,True,True
4,서울특별시 종로구 무악동,1101057,1111057000,11110,11,서울특별시,무악동,종로구,11010570,MULTIPOLYGON (((126.96067353273895 37.58079784...,1111057000,무악동,2.16,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,서울특별시 강동구 암사1동,1125072,1174057000,11740,11,서울특별시,암사1동,강동구,11250720,MULTIPOLYGON (((127.14447178485771 37.55477055...,1174057000,암사1동,0.55,NaN,True,True
422,서울특별시 강동구 천호2동,1125073,1174061000,11740,11,서울특별시,천호2동,강동구,11250730,MULTIPOLYGON (((127.13457783289466 37.54712046...,1174061000,천호2동,1.99,NaN,True,True
423,서울특별시 강동구 길동,1125074,1174068500,11740,11,서울특별시,길동,강동구,11250740,MULTIPOLYGON (((127.14856854982625 37.54577930...,1174068500,길동,4.11,NaN,True,True
424,서울특별시 구로구 오류2동,1117073,1153078000,11530,11,서울특별시,오류2동,구로구,11170730,MULTIPOLYGON (((126.8317936893084 37.477574560...,1153078000,오류2동,12.52,NaN,True,True
425,서울특별시 강동구 강일동,1125075,1174051500,11740,11,서울특별시,강일동,강동구,11250750,MULTIPOLYGON (((127.18187832639636 37.55885787...,1174051500,강일동,18.65,NaN,True,True

In [ ]:
park_df.rename(columns={'sggnm': '구'}, inplace=True)
park_df=park_df[['구','행정구역','세대당공원면적']]

In [ ]:
park_df.head()

     구 행정구역  세대당공원면적
0  종로구  사직동    60.79
1  종로구  삼청동   956.51
2  종로구  부암동     0.00
3  종로구  평창동     1.14
4  종로구  무악동     2.16

In [ ]:
resident_df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/행정동별 인구 관련 데이터/내가 만든 시각화 최종 파일 다른 파일들은 시각화에 쓴 파일들/just_residential_population_without_considering_dong_size_df.csv')
weekday_df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/행정동별 인구 관련 데이터/내가 만든 시각화 최종 파일 다른 파일들은 시각화에 쓴 파일들/weekday_live_population_df_considering_dong_size.csv')
weekend_df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/행정동별 인구 관련 데이터/내가 만든 시각화 최종 파일 다른 파일들은 시각화에 쓴 파일들/weekend_live_population_df_considering_dong_size.csv')

In [ ]:
resident_df.rename(columns={'읍면동명': '행정구역', '계': '전체인구수'}, inplace=True)
resident_df=resident_df[['행정구역','전체인구수']]

In [ ]:
weekday_df.rename(columns={'최종 행정동': '행정구역', '평균 생활인구수': '주중평균생활인구밀도'}, inplace=True)
weekday_df=weekday_df[['행정구역','주중평균생활인구밀도']]

In [ ]:
weekend_df.rename(columns={'최종 행정동': '행정구역', '평균 생활인구수': '주말평균생활인구밀도'}, inplace=True)
weekend_df=weekend_df[['행정구역','주말평균생활인구밀도']]

In [ ]:
print(len(sales_df))
print(len(park_df))
print(len(resident_df))
print(len(weekday_df))
print(len(weekend_df))

426
426
426
426
426

In [ ]:
# 각 DataFrame의 '행정구역' 집합 추출
sales_regions = set(sales_df['행정구역'])
park_regions = set(park_df['행정구역'])
resident_regions = set(resident_df['행정구역'])
weekday_regions = set(weekday_df['행정구역'])
weekend_regions = set(weekend_df['행정구역'])

# 다른 DataFrame에서 존재하지 않는 행정구역 찾기
sales_only = sales_regions - (park_regions | resident_regions | weekday_regions | weekend_regions)
park_only = park_regions - (sales_regions | resident_regions | weekday_regions | weekend_regions)
resident_only = resident_regions - (sales_regions | park_regions | weekday_regions | weekend_regions)
weekday_only = weekday_regions - (sales_regions | park_regions | resident_regions | weekend_regions)
weekend_only = weekend_regions - (sales_regions | park_regions | resident_regions | weekday_regions)

# 결과 출력
print("sales_df에만 있는 행정구역:", sales_only)
print("park_df에만 있는 행정구역:", park_only)
print("resident_df에만 있는 행정구역:", resident_only)
print("weekday_df에만 있는 행정구역:", weekday_only)
print("weekend_df에만 있는 행정구역:", weekend_only)

sales_df에만 있는 행정구역: {'상일1동', '상일2동'}
park_df에만 있는 행정구역: set()
resident_df에만 있는 행정구역: {'방화제1동', '신길제6동', '장위제1동', '길음제2동', '이촌제1동', '당산제1동', '자양제3동', '개봉제1동', '답십리제1동', '신길제4동', '신길제5동', '양평제1동', '고척제2동', '천호제2동', '성수2가제1동', '화곡제8동', '쌍문제2동', '창제3동', '대림제2동', '이문제1동', '구로제1동', '고덕제2동', '도봉제2동', '장안제1동', '망우제3동', '응암제1동', '방학제3동', '정릉제4동', '신대방제2동', '가양제1동', '구로제2동', '정릉제1동', '숭인제1동', '도봉제1동', '사당제2동', '창신제2동', '홍제제3동', '시흥제4동', '이문제2동', '묵제2동', '이태원제2동', '화곡제2동', '신사제1동', '월곡제2동', '노량진제2동', '등촌제3동', '성수1가제2동', '암사제2동', '면목제5동', '종로1.2.3.4가동', '창제5동', '발산제1동', '시흥제5동', '오류제1동', '창제4동', '화곡제6동', '북가좌제2동', '독산제4동', '구로제5동', '양평제2동', '전농제1동', '천호제3동', '이태원제1동', '고척제1동', '가양제2동', '성수1가제1동', '중화제1동', '금호2.3가동', '쌍문제3동', '성내제1동', '휘경제2동', '행당제2동', '개봉제3동', '홍은제2동', '남가좌제2동', '중계2.3동', '시흥제3동', '성산제2동', '중곡제4동', '답십리제2동', '구의제2동', '등촌제1동', '독산제2동', '왕십리제2동', '휘경제1동', '상도제3동', '면목제4동', '전농제2동', '둔촌제2동', '창신제3동', '쌍문제4동', '둔촌제1동', '원효로제1동', '상계6.7동', '독산제3동', '신길제1동', '중곡제2동', '당산제2동', '암사제3동', '사당제1동', '정릉제2동', '암사제1동', '자양제2동', '정릉제3동', '방화제2동', '행당제1동', '창제1동', '구의제1동', '화곡제1동', '사당제4동', '오류제2동', '성내제3동', '상계3.4동', '신대방제1동', '홍제제2동', '돈암제2동', '장위제2동', '망원제1동', '대림제1동', '상도제2동', '방화제3동', '자양제1동', '원효로제2동', '가양제3동', '종로5.6가동', '노량진제1동', '중곡제3동', '상봉제1동', '사당제3동', '신사제2동', '돈암제1동', '고덕제1동', '천호제1동', '숭인제2동', '면목제7동', '구로제4동', '신당제5동', '신길제3동', '시흥제2동', '시흥제1동', '성내제2동', '자양제4동', '북가좌제1동', '등촌제2동', '구로제3동', '남가좌제1동', '면목제3.8동', '길음제1동', '구의제3동', '성수2가제3동', '창신제1동', '이촌제2동', '중화제2동', '홍은제1동', '망원제2동', '신길제7동', '상도제4동', '중곡제1동', '홍제제1동', '묵제1동', '장안제2동', '독산제1동', '방학제2동', '응암제3동', '쌍문제1동', '화곡제4동', '갈현제2동', '면목제2동', '성산제1동', '갈현제1동', '월곡제1동', '장위제3동', '대림제3동', '상봉제2동', '불광제2동', '사당제5동', '명일제2동', '응암제2동', '창제2동', '화곡제3동', '개봉제2동', '불광제1동', '명일제1동', '방학제1동', '상도제1동'}
weekday_df에만 있는 행정구역: set()
weekend_df에만 있는 행정구역: set()

In [ ]:
sales_df.head()

   행정구역         추정매출액                                           geometry
0  가락1동  6.596725e+10  POLYGON ((209780.90485994637 544511.1612698265...
1  가락2동  5.505595e+10  POLYGON ((212324.33494913927 544030.4497464107...
2  가락본동  7.340508e+10  POLYGON ((211105.04751630727 543660.6932034456...
3  가리봉동  2.205196e+10  POLYGON ((189438.67265243208 543118.8918221833...
4   가산동  1.590000e+11  POLYGON ((189333.22378344863 542985.3764552184...

In [ ]:
park_df.head()

     구 행정구역  세대당공원면적
0  종로구  사직동    60.79
1  종로구  삼청동   956.51
2  종로구  부암동     0.00
3  종로구  평창동     1.14
4  종로구  무악동     2.16

In [ ]:
resident_df.head()

  행정구역  전체인구수
0  사직동   8993
1  삼청동   2229
2  부암동   9071
3  평창동  17231
4  무악동   7880

In [ ]:
weekday_df.head()

  행정구역    주중평균생활인구밀도
0  사직동  23261.546658
1  삼청동   6400.799714
2  부암동  11815.489584
3  평창동  17676.493775
4  무악동   5551.903145

In [ ]:
weekend_df.head()

  행정구역    주말평균생활인구밀도
0  사직동  23261.546658
1  삼청동   6400.799714
2  부암동  11815.489584
3  평창동  17676.493775
4  무악동   5551.903145

In [ ]:
# 첫 번째로 sales_df와 park_df를 합칩니다.
merged_df = pd.merge(sales_df, park_df, on='행정구역', how='left')

# 그 후, resident_df를 합칩니다.
merged_df = pd.merge(merged_df, resident_df, on='행정구역', how='left')

# 그 다음으로 weekday_df를 합칩니다.
merged_df = pd.merge(merged_df, weekday_df, on='행정구역', how='left')

# 마지막으로 weekend_df를 합칩니다.
merged_df = pd.merge(merged_df, weekend_df, on='행정구역', how='left')

In [ ]:
merged_df

,행정구역,추정매출액,geometry,구,세대당공원면적,전체인구수,주중평균생활인구밀도,주말평균생활인구밀도
0,가락1동,6.596725e+10,POLYGON ((209780.90485994637 544511.1612698265...,송파구,2.12,27396.0,30186.166318,30186.166318
1,가락2동,5.505595e+10,POLYGON ((212324.33494913927 544030.4497464107...,송파구,50.11,30960.0,24505.523853,24505.523853
2,가락본동,7.340508e+10,POLYGON ((211105.04751630727 543660.6932034456...,송파구,4.97,24932.0,34833.359938,34833.359938
3,가리봉동,2.205196e+10,POLYGON ((189438.67265243208 543118.8918221833...,구로구,0.00,8751.0,9842.003922,9842.003922
4,가산동,1.590000e+11,POLYGON ((189333.22378344863 542985.3764552184...,금천구,0.27,24938.0,42879.259792,42879.259792
...,...,...,...,...,...,...,...,...
421,후암동,2.158173e+10,POLYGON ((198120.59707234308 550412.6018005139...,용산구,0.29,15894.0,11517.017360,11517.017360
422,휘경1동,2.291680e+10,"POLYGON ((205759.1354219355 555091.1762696733,...",동대문구,0.21,NaN,16347.610727,16347.610727
423,휘경2동,1.817474e+10,POLYGON ((206325.71510806112 554272.9303041114...,동대문구,0.47,NaN,15533.131730,15533.131730
424,흑석동,4.789078e+10,POLYGON ((196739.24726459963 545861.9733953603...,동작구,27.15,30209.0,28647.009413,28647.009413
425,항동,1.002678e+10,"POLYGON ((184469.39368089964 543280.487797561,...",NaN,NaN,16239.0,49078.000000,49078.000000

In [ ]:
traffic_df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/여기까지 ㅠㅠ/total_총_승객수.csv')

In [ ]:
traffic_df.head()

    adm_cd         adm_nm     총_승객수
0  1101053  서울특별시 종로구 사직동  186527.0
1  1101054  서울특별시 종로구 삼청동   10357.0
2  1101055  서울특별시 종로구 부암동   14976.0
3  1101056  서울특별시 종로구 평창동   15634.0
4  1101057  서울특별시 종로구 무악동    4649.0

In [ ]:
traffic_df.loc[traffic_df['adm_nm'] == '서울특별시 강남구 신사동', 'adm_nm'] = '서울특별시 강남구 신사동1'
traffic_df.loc[traffic_df['adm_nm'] == '서울특별시 관악구 신사동', 'adm_nm'] = '서울특별시 관악구 신사동2'

In [ ]:
traffic_df['adm_nm'] = traffic_df['adm_nm'].str.split('구 ').str[1].str.strip()

In [ ]:
traffic_df.head()

    adm_cd adm_nm     총_승객수
0  1101053    사직동  186527.0
1  1101054    삼청동   10357.0
2  1101055    부암동   14976.0
3  1101056    평창동   15634.0
4  1101057    무악동    4649.0

In [ ]:
traffic_df.rename(columns={'adm_nm': '행정구역', 'adm_cd': '행정코드'}, inplace=True)

In [ ]:
merged_df = pd.merge(merged_df, traffic_df, on='행정구역', how='left')

In [ ]:
merged_df.head()

,행정구역,추정매출액,geometry,구,세대당공원면적,전체인구수,주중평균생활인구밀도,주말평균생활인구밀도,행정코드,총_승객수
0,가락1동,6.596725e+10,POLYGON ((209780.90485994637 544511.1612698265...,송파구,2.12,27396.0,30186.166318,30186.166318,1124066.0,68117.0
1,가락2동,5.505595e+10,POLYGON ((212324.33494913927 544030.4497464107...,송파구,50.11,30960.0,24505.523853,24505.523853,1124067.0,42065.0
2,가락본동,7.340508e+10,POLYGON ((211105.04751630727 543660.6932034456...,송파구,4.97,24932.0,34833.359938,34833.359938,1124065.0,19060.0
3,가리봉동,2.205196e+10,POLYGON ((189438.67265243208 543118.8918221833...,구로구,0.00,8751.0,9842.003922,9842.003922,1117070.0,15883.0
4,가산동,1.590000e+11,POLYGON ((189333.22378344863 542985.3764552184...,금천구,0.27,24938.0,42879.259792,42879.259792,1118051.0,182141.0

In [ ]:
merged_df=merged_df[['행정구역','행정코드','geometry','추정매출액','세대당공원면적','전체인구수','주중평균생활인구밀도','주말평균생활인구밀도','총_승객수']]

In [ ]:
merged_df.head()

,행정구역,행정코드,geometry,추정매출액,세대당공원면적,전체인구수,주중평균생활인구밀도,주말평균생활인구밀도,총_승객수
0,가락1동,1124066.0,POLYGON ((209780.90485994637 544511.1612698265...,6.596725e+10,2.12,27396.0,30186.166318,30186.166318,68117.0
1,가락2동,1124067.0,POLYGON ((212324.33494913927 544030.4497464107...,5.505595e+10,50.11,30960.0,24505.523853,24505.523853,42065.0
2,가락본동,1124065.0,POLYGON ((211105.04751630727 543660.6932034456...,7.340508e+10,4.97,24932.0,34833.359938,34833.359938,19060.0
3,가리봉동,1117070.0,POLYGON ((189438.67265243208 543118.8918221833...,2.205196e+10,0.00,8751.0,9842.003922,9842.003922,15883.0
4,가산동,1118051.0,POLYGON ((189333.22378344863 542985.3764552184...,1.590000e+11,0.27,24938.0,42879.259792,42879.259792,182141.0

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/Colab Notebooks/2024서울시빅캠/total_data.csv', index=False)